services:
  prometheus:
    image: seeker-prometheus
    ports:
      - '9090:9090'
    volumes:
      - prometheus-data:/prometheus
    restart: always
  grafana:
    image: seeker-grafana
    ports:
      - '3000:3000'
    depends_on:
      - prometheus
    restart: always
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./grafana-data:/var/lib/grafana

volumes:
  prometheus-data:
  grafana-data: