{
 "title": "System metrics",
 "description": "Metrics of windows like CPU usage, RAM usage etc.",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Up time", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "System uptime",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "avg_over_time(\r\n  (\r\n    sum without() (up{job=\"WMI_windows\"})\r\n      or\r\n    (0 * sum_over_time(up{job=\"WMI_windows\"}[7d]))\r\n  )[7d:5m]\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "CPU usage in percentage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "100 - (avg by (instance) (irate(windows_cpu_time_total{mode=\"idle\"}[1m])) * 100)",
     "legendFormat": "__auto"
    },
    { "expression": "A", "reducer": "last", "type": "reduce" }
   ]
  },
  {
   "title": "CPU usage in percentage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (avg by (instance) (irate(windows_cpu_time_total{mode=\"idle\"}[1m])) * 100)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "RAM", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "RAM usage in GB",
   "type": "timeseries",
   "description": "total RAM and used space in GB",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "windows_memory_physical_total_bytes/1000000000",
     "legendFormat": "total memory"
    },
    {
     "expr": "(windows_memory_physical_total_bytes-windows_memory_physical_free_bytes)/1000000000",
     "legendFormat": "memory used"
    }
   ]
  },
  {
   "title": " free  RAM memory in GB",
   "type": "timeseries",
   "description": "Available RAM memory",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "targets": [
    {
     "expr": "windows_memory_physical_free_bytes/1000000000",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "DIsk", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Total Disk memory in GB",
   "type": "timeseries",
   "description": "Hard disk memory with partitions ",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "windows_logical_disk_size_bytes/1000000000",
     "legendFormat": "{{volume}}"
    },
    {
     "expr": "sum by(instance) (windows_logical_disk_size_bytes/1000000000)",
     "legendFormat": "System total memory"
    }
   ]
  },
  {
   "title": "DIsk Usage in GB",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
   "targets": [
    {
     "expr": "(windows_logical_disk_size_bytes-windows_logical_disk_free_bytes)/1000000000",
     "legendFormat": "{{volume}}"
    },
    {
     "expr": "sum by(instance)(windows_logical_disk_size_bytes-windows_logical_disk_free_bytes)/1000000000",
     "legendFormat": "Total DIsk usage"
    }
   ]
  },
  {
   "title": "Available memory in GB",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 36 },
   "targets": [
    {
     "expr": "sum by(instance)(windows_logical_disk_free_bytes/1000000000)",
     "legendFormat": "__auto"
    },
    { "expression": "A", "reducer": "last", "type": "reduce" }
   ]
  }
 ]
}